// Company-discovery engine — shared logic for expanding tracked_companies.
//
// The reusable heart is ATS detection: given a company NAME, guess slug variants
// and probe Greenhouse / Lever / Ashby (reusing the real provider fetchers in
// quiet mode). Whichever returns jobs is the true ATS + slug. Because the probe
// is ground truth, upstream candidate generation can be fuzzy — a wrong guess or
// an LLM-invented company simply fails the probe and is dropped.
//
// Two candidate sources feed the same engine:
//   - paste:   names supplied by the user
//   - suggest: names generated by Claude in the user's target domains
//
// Non-obvious slugs (that a name-guess misses) get one web_search fallback each,
// capped by the caller. Anthropic calls go through fetchWithRetry (retry on
// 429/503/529). Nothing here touches the DB — the function layer does the writes.

import { detectGreenhouse, fetchGreenhouse } from '../providers/greenhouse.js';
import { detectLever, fetchLever } from '../providers/lever.js';
import { detectAshby, fetchAshby } from '../providers/ashby.js';
import { fetchWithRetry } from './http.js';

// Built-in fallback for the suggest-mode system prompt. Used (with a logged
// warning) when COMPANY_DISCOVER_PROMPT is unset, so the feature works without
// setup but the fallback is visible in logs.
export const DEFAULT_DISCOVER_PROMPT =
  `You suggest real companies a Product Manager should consider, matching a ` +
  `candidate's target domains. Only propose companies you are confident actually ` +
  `exist and are operating today. Favor companies likely to hire REMOTE Product ` +
  `Managers and to run a standard applicant tracking system (Greenhouse, Lever, ` +
  `or Ashby). Never invent companies. Never repeat a company on the exclude list. ` +
  `Return only the requested JSON array, no prose.`;

const PROBERS = [
  { provider: 'greenhouse', careers: s => `https://job-boards.greenhouse.io/${s}`, fetch: fetchGreenhouse },
  { provider: 'lever',      careers: s => `https://jobs.lever.co/${s}`,            fetch: fetchLever },
  { provider: 'ashby',      careers: s => `https://jobs.ashbyhq.com/${s}`,         fetch: fetchAshby },
];

const LEGAL_SUFFIX = /\b(inc|incorporated|llc|ltd|limited|corp|corporation|company|co|gmbh|plc|sa|pllc|lp|llp|pvt|pte)\b/g;

// Two slug variants from a company name: bare-alphanumeric and hyphenated.
export function slugVariants(name) {
  const base = (name || '').toLowerCase().replace(/[.,]/g, ' ').replace(LEGAL_SUFFIX, ' ').trim();
  const alnum = base.replace(/[^a-z0-9]+/g, '');
  const hyphen = base.replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return [...new Set([alnum, hyphen].filter(s => s.length >= 2))];
}

// Probe a company name across all three ATSs (quiet — misses are expected).
// Returns { provider, slug, careers_url, jobs } on the first hit, else null.
export async function detectAts(name) {
  for (const slug of slugVariants(name)) {
    for (const p of PROBERS) {
      const careers_url = p.careers(slug);
      let jobs = [];
      try { jobs = await p.fetch({ name, careers_url }, { quiet: true }); } catch { jobs = []; }
      if (jobs && jobs.length) return { provider: p.provider, slug, careers_url, jobs };
    }
  }
  return null;
}

// Probe a specific provider+slug (used to confirm a web_search fallback result).
export async function probeSlug(name, provider, slug) {
  const p = PROBERS.find(x => x.provider === provider);
  if (!p || !slug) return null;
  const careers_url = p.careers(slug);
  let jobs = [];
  try { jobs = await p.fetch({ name, careers_url }, { quiet: true }); } catch { jobs = []; }
  return jobs && jobs.length ? { provider, slug, careers_url, jobs } : null;
}

// Count how many of a company's jobs pass the user's title filter (PM relevance).
export function relevanceCheck(jobs, positive = [], negative = []) {
  const matches = (jobs || []).filter(j => titlePass(j.title, positive, negative));
  return { count: matches.length, sample: matches[0]?.title || null };
}

function titlePass(title, positive, negative) {
  if (!title) return false;
  const t = title.toLowerCase();
  for (const n of negative) if (n && t.includes(n.toLowerCase())) return false;
  if (!positive.length) return true;
  for (const p of positive) if (p && t.includes(p.toLowerCase())) return true;
  return false;
}

// suggest mode: ask Claude for candidate companies in the user's domains.
export async function generateCandidates({ env, profileText, existingNames, count, prompt, model }) {
  const user = [
    `TARGET PROFILE / DOMAINS:`,
    profileText || '(none provided)',
    ``,
    `ALREADY TRACKED (exclude all of these): ${existingNames.length ? existingNames.join(', ') : '(none)'}`,
    ``,
    `Propose up to ${count} additional companies that fit the domains above and are likely to hire remote Product Managers.`,
    `Return ONLY a JSON array: [{"name":"Company","domain":"short domain tag"}]`,
  ].join('\n');

  const data = await anthropic(env, {
    model,
    max_tokens: 1500,
    system: prompt,
    messages: [{ role: 'user', content: user }],
  });
  if (!data) return [];
  return parseJsonArray(lastText(data))
    .filter(c => c && c.name)
    .map(c => ({ name: String(c.name).trim(), domain: c.domain ? String(c.domain).trim() : null }));
}

// Fallback: one web_search call to find a company's Greenhouse/Lever/Ashby slug.
// Returns { provider, slug } or null. Caller must confirm with probeSlug().
export async function webSearchAts({ env, name, model }) {
  const system =
    `You find a company's public job board and identify its ATS. Use web search to ` +
    `locate the company's careers/jobs page. If it posts on Greenhouse, Lever, or ` +
    `Ashby, return the board slug (the path segment: job-boards.greenhouse.io/ACME, ` +
    `jobs.lever.co/ACME, or jobs.ashbyhq.com/ACME → "ACME"). If you cannot confirm ` +
    `one of those three, return provider "none". Return ONLY JSON: ` +
    `{"provider":"greenhouse|lever|ashby|none","slug":"<slug or empty>"}`;

  const data = await anthropic(env, {
    model,
    max_tokens: 300,
    system,
    tools: [{ type: 'web_search_20250305', name: 'web_search', max_uses: 3 }],
    messages: [{ role: 'user', content: `Company: ${name}\nFind its Greenhouse/Lever/Ashby job-board slug.` }],
  });
  if (!data) return null;
  const parsed = parseJsonObject(lastText(data));
  if (!parsed || !['greenhouse', 'lever', 'ashby'].includes(parsed.provider) || !parsed.slug) return null;
  return { provider: parsed.provider, slug: String(parsed.slug).trim() };
}

// ── Anthropic + JSON helpers ──────────────────────────────────────────────────

async function anthropic(env, bodyObj) {
  let res;
  try {
    res = await fetchWithRetry('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': env.anthropicKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify(bodyObj),
    }, { allowNonGet: true, retryStatuses: [429, 503, 529], label: 'anthropic discover' });
  } catch (e) {
    console.error('discover: anthropic call failed:', e.message);
    return null;
  }
  if (!res.ok) {
    const b = await res.text().catch(() => '');
    console.error(`discover: anthropic HTTP ${res.status}`, b.slice(0, 200));
    return null;
  }
  return res.json();
}

// Last text block, stripped of code fences (mirrors company-scan / score.js).
function lastText(data) {
  const blocks = (data?.content || []).filter(b => b.type === 'text');
  return (blocks[blocks.length - 1]?.text || '').trim()
    .replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
}

function parseJsonArray(text) {
  try { const v = JSON.parse(text); return Array.isArray(v) ? v : []; } catch { return []; }
}

function parseJsonObject(text) {
  try { const v = JSON.parse(text); return v && typeof v === 'object' && !Array.isArray(v) ? v : null; } catch { return null; }
}

// Re-exported so the caller can also detect providers if ever needed.
export { detectGreenhouse, detectLever, detectAshby };
